#!/bin/bash

[ -z "$CONTROL_PATH" ] && CONTROL_PATH="opal-toolset"
CONTROL=$CONTROL_PATH/control
[ ! -f "$CONTROL" ] && printf "Invalid path $CONTROL.\n" && exit 1

[ -z "$DEV" ] && printf "WARNING: Variable DEV must be defined (partition or block device), test skipped.\n" && exit 1
[ -z "$PIN" ] && printf "WARNING: Variable PIN must be defined (PSID in hexadecimal), test skipped.\n" && exit 1

printf "Resetting the device...\n\n"

$CONTROL -V psid_revert $DEV --verify-pin-hex=$PIN || { printf "\nPSID reset failed.\n" && exit 1; }

printf "\nDone.\n"
